app:
  # 日志记录类型：SERVER、FILE、CONSOLE，如果是使用Docker安装建议留空或者设置为CONSOLE；如果是使用群晖套件建议配置为 SERVER，可将日志输出到群晖的日志中心便于查看；如果是python本地运行建议设置为FILE，保存日志到文件。
  logtype: CONSOLE
  # 日志文件的路径，logtype为FILE时生效
  logpath: '/config/logs'
  # 群晖日志中心IP和端口，logtype为SERVER时生效。端口一般是514，只需要改动IP为群晖的IP。
  logserver: 127.0.0.1:514
  # WEB管理界面端口，默认3000
  web_port: 3000
  # WEB管理页面登录用户，默认admin
  login_user: admin
  # WEB管理页面登录用户密码，默认password
  login_password: password
  # WEB管理界面使用的HTTPS的证书和KEY的路径，留空则不启用HTTPS
  ssl_cert:
  ssl_key:
  # 存储媒体库设备的操作系统类型：Windows、Linux，用于监控目录变化。Windows类型性能比较差，会导致NAS不能休眠，除非NAS是Windows的否则都建议配置为Linux
  nas_sys: Linux

media:
  # 媒体库电影文件存放目录，docker使用需要将NAS储存目录映射到以下路径
  movie_path: '/mnt/media/电影'
  # 媒体库电视剧文件存放目录，docker使用需要将NAS储存目录映射到以下路径
  tv_path: '/mnt/media/电视剧'
  # 媒体库预告片存放目录，会去themoviedb搜刮新出的电影预告并下载，有对应电影存在时会优先转移到电影目录。不配置则不启用热门预告片下载功能。
  hottrailer_path: '/mnt/media/预告'
  # ResilioSync同步文件夹监控目录，可以监控多个目录，以数组形式配置，可以用 - 自己添加多个条目，需要与resiliosync同步目录一致。不配置则不启用热门预告片下载功能。
  resiliosync_path:
    - '/mnt/resiliosync/大片抢先看'

qbittorrent:
  # qBittorrent IP地址和端口，注意如果qb启动了HTTPS证书，则需要配置为https://IP
  qbhost: 10.10.10.250
  qbport: 8080
  # qBittorrent 登录用户名和密码
  qbusername: admin
  qbpassword: password
  # qBittorrent下载保存目录，如果是Docker版本的qBittorrent这个是容器内的路径。
  save_path: '/volume2/PT/'
  # 如果本程序是用Docker运行，则这个是PT下载目录对应映射到本程序Docker容器内的路径，否则留空即可。
  save_containerpath:

message:
  # 发送消息使用的渠道：wechat、serverchan、telegram，需在对应的配置区域配置。不使用的渠道配置可以留空或者删除。推荐使用wechat微信渠道。不设置则不启用消息服务。
  msg_channel: wechat
  # 配置了Emby webhooks插件回调时，用户播放媒体库中的媒体时会发送消息通知，本处配置哪些用户的设备不通知，避免打扰，配置格式：用户:设备名称，可用 - 增加多项
  webhook_ignore:
    - 'admin:xx的iPhone 12'
  wechat:
    # 企业微信消息应用，在企业微信https://work.weixin.qq.com/中申请和新增一个自建应用。配合微信的企业微信插件，可以直接在微信中查看本程序的消息以及控制程序运行，非常好用，推荐使用该渠道。
    # corpid:每个企业都拥有唯一的corpid，获取此信息可在管理后台“我的企业”－“企业信息”下查看“企业ID”（需要有管理员权限）
    # corpsecret:自建应用secret。在管理后台->“应用与小程序”->“应用”->“自建”，点进某个应用，即可看到。
    # agentid:每个应用都有唯一的agentid。在管理后台->“应用与小程序”->“应用”，点进某个应用，即可看到agentid。
    # 具体不明白的参考企业微信的开发者中心，
    corpid:
    corpsecret:
    agentid:
    # 微信回调，用于在微信中控制本程序，需要在企业微信https://work.weixin.qq.com/中设置自建应用的菜单等。
    Token:
    EncodingAESKey:

  serverchan:
    # ServerChan API KEY，SCT类型，在https://sct.ftqq.com/中申请（非VIP貌似每日限制只能收到5条消息）
    sckey:

  telegram:
    # Telegram机器人，需要在Telegram中创建机器人以及获取chat_id
    telegram_token:
    telegram_chat_id:

pt:
  # PT下载完成后转移到媒体库的转移模式：COPY复制模式、LINK硬链接模式。复制模式下载做种和媒体库是两份，多占用存储（下载盘大小决定能保多少种），好处是媒体库的盘不用24小时运行可以休眠；硬链接模式不用额外增加存储空间，一份文件两份目录，但需要下载目录和媒体库目录在一个磁盘分区或者存储空间。两者在媒体库使用上是一致的。
  rmt_mode: COPY
  # TMDB API KEY，需要在https://www.themoviedb.org/申请，必须配置这个，否则无法识别媒体资源和重命名
  rmt_tmdbkey:
  # 配置PT站点的信息，RSS用于订阅自动下载，COOKIE用于签到
  # 是否只下载有中文媒体信息的种子（开了只会下themoviedb有中文描述的影视资源）
  rss_chinese: False
  # PT站每日签到的时间
  ptsignin_cron: 8:00
  # PT做种时间，做种超过该时间则会自动删种（包括已下载的文件），单位是秒。如果是使用COPY模式，这个根据PT下载盘的大小配置，如果是使用LINK模式，这个可以不配，不配置或者配置为0则不启用删种功能。
  pt_seeding_time: 86400
  # RSS检查时间间隔，即每隔多长时间检查一下各PT站是否有资源更新，建议不要少于10分钟，单位时间为秒。
  pt_check_interval: 1800
  # PT站的信息，理论上支持所有PT站点，可按示例格式增加其他站点的配置，URL、正则式、Cookie等注意加引号，不然容易造成格式错误。
  sites:
    pthome:
      # RSS订阅源URL，可以是点击PT站点RSS图标获取，注意不要选中类型、小标题等内容，避免干扰识别，有新出资源时自动匹配下载；也可以是PT站的购物车/下载框的链接（部分站点才有）。
      rssurl:
      # PT站中类型为电影的类别关键字，未匹配该关键字的则为剧集，不同的PT站这个类型的叫法可能不同，有的叫Movie有的是繁体，请按PT站实际情况修改尝试。可用 - 增加多个。
      movie_type:
        - '电影'
      # 电影过滤关键字，可以为正式表达式，也可以是电影的名称，程序会用这个配置去匹配种子文件名和识别后的电影标题，匹配到则会自动下载，可用 - 增加多个。默认配置会匹配所有2021、2022年新出的电影。注意正则式要用''括起来。
      movie_re:
        - '[\s\.]+2021|2022[\s\.]+'
      # 电视剧过滤关键字，可以为正式表达式，也可以是电视剧的名称，程序会用这个配置去匹配种子文件名和识别后的电视剧标题，匹配到则会自动下载，可用 - 增加多个
      tv_re:
        - 'Ousama Ranking 2021'
        - '进击的巨人'
      # PT站用户签到的Url，一般为mybonus.php或attendance.php，即PT站点签到按钮跳转的页面，不配置则不启用签到功能
      signin_url: 'https://pthome.net/attendance.php'
      # PT站的Cookie，需要在浏览器中F12->网络 页抓取，具体操作可百度，未配置则无法进行PT签到
      cookie:
    m-team:
      rssurl:
      movie_type:
       - 'Movie(電影)/HD'
      movie_re:
        - '[\s\.]+2021|2022[\s\.]+'
      tv_re:
      signin_url: 'https://kp.m-team.cc/mybonus.php'
      cookie:
    ptsbao:
      rssurl:
      movie_type:
        - '电影'
      movie_re:
        - '[\s\.]+2021|2022[\s\.]+'
      tv_re:
      signin_url: 'https://ptsbao.club/mybonus.php'
      cookie:
