# 硬链接模式的配置文件，只有两个功能：1、监控下载软件，下载完成后自动识别重命名并做硬链接/复制。2、监控目录，目录有变化时自动识别重命名和做硬链接/复制，没有UI界面，但可以保留通知。
# 【配置注意要符合yaml语法，:号后有1个空格，不能使用全角标点符号】
app:
  # 这个配置不要改
  simple_mode: true
  # TMDB API KEY，需要在https://www.themoviedb.org/申请，必须配置这个，否则无法识别媒体资源和重命名
  # 以下地址需要网络能够正常访问：api.themoviedb.org、images.weserv.nl、webservice.fanart.tv
  rmt_tmdbkey:
  # TMDB匹配模式：normal、strict，normal模式下如使用文件名/种子名中的年份无法匹配到媒体信息，会去掉年份再匹配一次；strict模式则严格按文件中年份匹配
  # normal模式下会提升识别成功率，但也可能会导致误识别率增加；strict模式可以降低误识别率，但可能导致很多文件名/种子名中年份不正确的无法被识别（特别是剧集，需要是首播年份）
  rmt_match_mode: normal

# 配置媒体库目录等信息，不能删除
media:
  # 媒体库电影文件存放目录
  movie_path: '/mnt/media/电影'
  # 媒体库电视剧文件存放目录
  tv_path: '/mnt/media/电视剧'
  # 媒体库动漫文件存放目录
  # 动漫电影会在电影分类下，多集动漫实际上有两种类型，一是PT站以常规PT资源格式命名的，这类会按电视剧识别（在TMDB中也是电视剧），按默认分类会存在电视剧/动漫目录中；另一种是日漫格式命名，这类会使用aniopy模块按动漫类型识别，会单独读取anime_path做为存放目录
  # 如果以上两种情况都存在，且使用默认分类规则，建议anime_path设置为电视剧下面的动漫子目录或者直接不配置该项（不配置时仍然按电视剧分类处理），否则会出现动漫分在两个目录的问题
  anime_path: '/mnt/media/电视剧/动漫'
  # 无法识别时转移存放的目录，适用于PT下载转移以及sync未指明目的目录时的情况
  unknown_path: '/mnt/media/unknown'
  # 电影电视剧是否需要二级分类，启用二级分类后会在电影电视剧目录下按二级分类名建立子目录
  # 此处配置分类的策略名，配置文件目录中需要有与策略名同名的配置文件，配置模板可参考default-category.yaml
  # 默认策略default-category分类设置可参考README.MD说明
  category: 'default-category'

# 配置文件夹监控，文件夹内容发生变化时自动识别转移
sync:
  # 监控目录，可以监控多个。监控目录有文件变化时会自动进行媒体识别、转移并命名
  # 配置格式1：'源目录|目的目录'，比如：'/mnt/movie1|/mnt/mymovie'，配了目的目录时，会转移到/mnt/mymovie目的目录中，不自动区分电影或电视剧
  # 配置格式2：'源目录'，比如：'/mnt/movie1'，目的目录不配时会自动识别是电影还是电视剧并转移到media中配置的movie_path、tv_path、anime_path配置的目录中（开了自动分类的话会在该目录下进行二级目录分类）
  # 如果无法识别文件媒体信息，配置了目的目录的情况下会LINK到目的目录的unknown录下
  # 建议映射上级目录，源目录和目的目录为子目录，如果分开映射则可能发生跨盘的问题
  # 启动监控报错的，参考WIKI中的常见问题
  sync_path:
    - '/mnt/movie1|/mnt/mymovie'
    - '/mnt/movie2|/mnt/mymovie'
    - '/mnt/resiliosync/大片抢先看'
  # 监控目录文件的转移方式：link、copy、softlink，link即硬链接、softlink为软链接，copy为复制，均会重命名
  # link要求源目录和目的目录或媒体库目录在一个磁盘分区或者存储空间，Docker运行时link模式需要直接映射源目录和目的目录或媒体库目录的上级目录，否则docker可能仍然会认为是跨盘
  # softlink模式注意宿主机的源目录映射到docker容器中后要路径要一致，否则可能软链接成功但无法在宿主机使用
  sync_mod: link

# 配置消息通知服务，不需要可以删除
message:
  # 发送消息使用的渠道：wechat、serverchan、telegram，需在对应的配置区域配置。不使用的渠道配置可以留空或者删除。推荐使用wechat微信渠道。不设置则不启用消息服务。
  msg_channel: wechat
  # 【推荐】企业微信消息应用，在企业微信https://work.weixin.qq.com/中申请和新增一个自建应用。配合微信的企业微信插件，可以直接在微信中查看本程序的消息以及控制程序运行，非常好用，推荐使用该渠道。
  wechat:
    # corpid:每个企业都拥有唯一的corpid，获取此信息可在管理后台“我的企业”－“企业信息”下查看“企业ID”（需要有管理员权限）
    # corpsecret:自建应用secret。在管理后台->“应用与小程序”->“应用”->“自建”，点进某个应用，即可看到。
    # agentid:每个应用都有唯一的agentid。在管理后台->“应用与小程序”->“应用”，点进某个应用，即可看到agentid。
    # 具体不明白的参考企业微信的开发者中心，
    corpid:
    corpsecret:
    agentid:
    # 微信回调，用于在微信中控制本程序，需要在企业微信https://work.weixin.qq.com/中设置自建应用的菜单等。
    # 步聚：1、在微信企业应用接收消息设置页面生成Token和EncodingAESKey并填入下面区域。2、重启本程序。3、在微信企业应用接收消息设置页面输入此地址：http(s)://ip:3000/wechat。需要有公网IP并做好端口转发，最好要有域名。
    Token:
    EncodingAESKey:
  # ServerChan API KEY，SCT类型，在https://sct.ftqq.com/中申请（非VIP貌似每日限制只能收到5条消息）
  serverchan:
    sckey:
  # Telegram机器人，需要在Telegram中创建机器人以及获取chat_id
  telegram:
    # telegram机器人的Token，关注BotFather创建机器人
    telegram_token:
    # telegram关注getuserID获取
    telegram_chat_id:
  # Bark通知，手机上安装Bark客户端，Server可以使用默认的也可以自己搭建，自己搭建的更换为服务器地址和端口，格式：http(s)://IP:PORT。
  bark:
    # 自己搭建请更换，否则保持默认
    server: https://api.day.app
    # Bark客户端生成的KEY
    apikey:

# 配置PT下载信息，用于监控下载软件，完成后自动转移和改名，不用可删掉
pt:
  # PT下载完成后转移到媒体库的转移模式：copy复制模式、link硬链接模式、softlink软链接模式，均会重命名
  # copy下载做种和媒体库是两份，多占用存储（下载盘大小决定能保多少种），好处是媒体库的盘不用24小时运行可以休眠
  # link模式不用额外增加存储空间，一份文件两份目录（显示的大小一样），但需要下载目录和媒体库目录在一个磁盘分区或者存储空间，Docker运行时link模式需要直接映射源目录和目的目录或媒体库目录的上级目录，否则docker可能仍然会认为是跨盘
  # softlink模式注意宿主机的源目录映射到docker容器中后要路径要一致，否则可能软链接成功但无法在宿主机使用
  rmt_mode: link
  # PT下载使用的客户端软件，qbittorrent、transmission，需要配置qbittorrent或transmission对应的配置区域，使用一个后另一个配置可以删掉
  pt_client: qbittorrent
  # 是否监控PT下载软件：true、false，如为true则PT下载完成会自动转移和重命名，如为false则不会处理
  # PT下载软件监控与Sync下载目录监控不要同时开启，否则会处理两遍
  pt_monitor: true

# 配置qBittorrent下载软件，不用可删掉
qbittorrent:
  # qBittorrent IP地址和端口，注意如果qb启动了HTTPS证书，则需要配置为https://IP
  qbhost: 127.0.0.1
  qbport: 8080
  # qBittorrent 登录用户名和密码
  qbusername: admin
  qbpassword: adminadmin
  ## 下面两项配置问的人比较多，解释一下：
  # 1、save_path是nastool检索到需要新增下载时告诉qb下到哪个目录去，是传给qb的
  # 2、save_containerpath是告诉nastool qb的下载路径对应在nastool里又是映射为什么路径，这样nastool才能通过这个路径访问到qb下载好的文件
  # qBittorrent下载保存目录，如果是Docker版本的qb这个是容器内的路径
  ## 有两种配置方法：
  # 1、直接在：号后面配置一个路径（删掉下面的movie、tv项），则所有电影电视剧均下载到这个目录中
  # 2、在save_path下面配置子栏目，可以按电影、电视剧分开目录存储，当然也可以配置成同一个目录
  # 如果需要该配置生效，QB的下载管理模式需要为自动
  save_path:
    movie:
    tv:
    anime:
  # 1、如果本程序是用Docker运行，则这个是PT下载目录对应映射到本程序Docker容器内的路径
  # 2、如果本程序不是Docker运行但qb是Docker运行，则设置为PT下载目录在宿主机上的真实路径
  # 3、不是以上两种情况留空即可
  # 配置项需要跟save_path一一对应
  save_containerpath:
    movie:
    tv:
    anime:

# 配置transmission下载软件 需要3.0以上版本，否则可能会报错
transmission:
  # transmission IP地址和端口，注意如果tr启用了HTTPS证书，则需要配置为https://IP
  trhost: 127.0.0.1
  trport: 9091
  # transmission 登录用户名和密码
  trusername: admin
  trpassword: password
  ## 下面两项配置问的人比较多，解释一下：
  # 1、save_path是nastool检索到需要新增下载时告诉tr下到哪个目录去，是传给tr的
  # 2、save_containerpath是告诉nastool tr的下载路径对应在nastool里又是映射为什么路径，这样nastool才能通过这个路径访问到tr下载好的文件
  # transmission下载保存目录，如果是Docker版本的tr这个是容器内的路径
  ## 有两种配置方法：
  # 1、直接在：号后面配置一个路径（删掉下面的movie、tv项），则所有电影电视剧均下载到这个目录中
  # 2、在save_path下面配置子栏目，可以按电影、电视剧分开目录存储，当然也可以配置成同一个目录
  save_path:
    movie:
    tv:
    anime:
  # 1、如果本程序是用Docker运行，则这个是PT下载目录对应映射到本程序Docker容器内的路径
  # 2、如果本程序不是Docker运行但tr是Docker运行，则设置为PT下载目录在宿主机上的真实路径
  # 3、不是以上两种情况留空即可
  # 配置项需要跟save_path一一对应
  save_containerpath:
    movie:
    tv:
    anime: