"""1_1_1

Revision ID: 42ffdc3c7f55
Revises: 720a6289a697
Create Date: 2024-05-01 16:34:08.535885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42ffdc3c7f55'
down_revision = '720a6289a697'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CONFIG_SITE', sa.Column('apikey', sa.Text(), nullable=True))
    op.add_column('CONFIG_SITE', sa.Column('token', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('CONFIG_SITE', 'token')
    op.drop_column('CONFIG_SITE', 'apikey')
    # ### end Alembic commands ###
